### ISSUE TITLE
[blocklink-addon] Traceback

### ISSUE THREAD

**Issue by GreenLunar** [mozbugbox/liferea-plugin-studio#1]
On enabling:
```
Traceback (most recent call last):
  File "/home/HOSTNAME/.local/share/liferea/plugins/blocklink-addon/blocklinkaddon.py", line 569, in do_activate
    current_views = self.current_webviews
  File "/home/HOSTNAME/.local/share/liferea/plugins/blocklink-addon/blocklinkaddon.py", line 548, in current_webviews
    html_in_tabs = [x.htmlview for x in browser_tabs.props.tab_info_list]
TypeError: 'NoneType' object is not iterable
```

On disabling:
```
Traceback (most recent call last):
  File "/home/HOSTNAME/.local/share/liferea/plugins/blocklink-addon/blocklinkaddon.py", line 580, in do_deactivate
    current_views = self.current_webviews
  File "/home/HOSTNAME/.local/share/liferea/plugins/blocklink-addon/blocklinkaddon.py", line 548, in current_webviews
    html_in_tabs = [x.htmlview for x in browser_tabs.props.tab_info_list]
TypeError: 'NoneType' object is not iterable
```

**Comment by mozbugbox** [comment]
I cannot reproduce the backtrace. Which version of liferea are you using? `browser_tabs.props.tab_info_list` should be an empty list as `[]` when no tab presented. Should not be `None` in any case.

**Comment by GreenLunar** [comment]
Liferea 1.11.3

**Comment by mozbugbox** [comment]
Well, version 1.11.3 won't work. You have to use version 1.11.4 or the current git master because the webkit related plugins need commit lwindolf/liferea@9eafdd1d20540cdcd1d33038e5b276f3afa981f1 and some other commits to function properly.

**Comment by GreenLunar** [comment]
I will reopen if issue persists.

**Comment by GreenLunar** [comment]
On enabling:
```
Traceback (most recent call last):
  File "/home/HOSTNAME/.local/share/liferea/plugins/blocklink-addon/blocklinkaddon.py", line 574, in do_activate
    current_views = self.current_webviews
  File "/home/HOSTNAME/.local/share/liferea/plugins/blocklink-addon/blocklinkaddon.py", line 552, in current_webviews
    html_in_tabs = [x.htmlview for x in browser_tabs.props.tab_info_list]
TypeError: 'NoneType' object is not iterable
```

On disabling:
```
Traceback (most recent call last):
  File "/home/HOSTNAME/.local/share/liferea/plugins/blocklink-addon/blocklinkaddon.py", line 585, in do_deactivate
    current_views = self.current_webviews
  File "/home/HOSTNAME/.local/share/liferea/plugins/blocklink-addon/blocklinkaddon.py", line 552, in current_webviews
    html_in_tabs = [x.htmlview for x in browser_tabs.props.tab_info_list]
TypeError: 'NoneType' object is not iterable
```

On clicking on Preferences button:
```
(liferea:3745): libpeas-CRITICAL **: show_configure_cb: assertion `GTK_IS_WIDGET (conf_widget)' failed
```
