### ISSUE TITLE
Accel dump fails - 'Window' object has no attribute 'list_actions'

### ISSUE THREAD

**Issue by psukys** [mozbugbox/liferea-plugin-studio#11]
After pressing the *Dump Accels* button, nothing happened. Checked by running from console, it spit the following error

```
Traceback (most recent call last):
  File "/home/sukys/.local/share/liferea/plugins/accels/accels.py", line 171, in _on_dump_button_clicked
    actions = self.get_actions()
  File "/home/sukys/.local/share/liferea/plugins/accels/accels.py", line 145, in get_actions
    win_actions = mainwin.list_actions()
AttributeError: 'Window' object has no attribute 'list_actions'
```

Liferea version: 1.12.2 (From Ubuntu 18.04 LTS repos)

**Comment by psukys** [comment]
Did not notice in README that plugins support >= 1.12.3..
After upgrading Liferea, the problem is no more
