### ISSUE TITLE
[webkit-setting] Traceback

### ISSUE THREAD

**Issue by GreenLunar** [mozbugbox/liferea-plugin-studio#3]
On enabling:
```
Traceback (most recent call last):
  File "/home/HOSTNAME/.local/share/liferea/plugins/webkit-setting/webkitsetting.py", line 219, in do_activate
    current_views = self.current_webviews
  File "/home/HOSTNAME/.local/share/liferea/plugins/webkit-setting/webkitsetting.py", line 275, in current_webviews
    html_in_tabs = [x.htmlview for x in browser_tabs.props.tab_info_list]
TypeError: 'NoneType' object is not iterable
```

On disabling:
```
Traceback (most recent call last):
  File "/home/HOSTNAME/.local/share/liferea/plugins/webkit-setting/webkitsetting.py", line 233, in do_deactivate
    self.unconfig_soup()
  File "/home/HOSTNAME/.local/share/liferea/plugins/webkit-setting/webkitsetting.py", line 385, in unconfig_soup
    soup_session.disconnect(soup_session.request_queued_cid)
AttributeError: 'SessionAsync' object has no attribute 'request_queued_cid'
```

**Comment by lwindolf** [comment]
PR #10 fixes this
